# Generated by Django 2.0.6 on 2019-03-04 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=20)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
